# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job:
    name: ${{ matrix.os }} ${{ matrix.cc }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
          - os: ubuntu-latest
            cc: gcc
            cxx: g++
          - os: ubuntu-latest
            cc: clang
            cxx: clang++
          - os: macos-latest
        
    env:
      CC: ${{ matrix.cc }}
      CXX: ${{ matrix.cxx }}
        
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive  
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt install -y libgl1-mesa-dev
        if: matrix.os == 'ubuntu-latest'
        
      - uses: BSFishy/meson-build@v1.0.3
        with:
          action: build
          directory: build
          setup-options: --buildtype=release
